### ISSUE TITLE
theme sdk:  add ‘--window border color’ CSS variables

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5758]
## Problem description

It is suggested to add a variable to change the  `--window-border-color`.   

```css
    --window-border-size: 1px;
    --window-border-color: #30363d  /* Not currently support */
```

Currently, the border color of the dialog is fixed to `#ccc`.  is not supported to changed.

![Snipaste_2022-06-02_15-05-28](https://user-images.githubusercontent.com/45864744/171572850-3738e59a-62eb-4c34-98cc-8091107cd37e.png)

Doesn't work even if I specify border color.
```css
dialog {
    border-color:#30363d;
}
```

Of course, I can also force it to change, but that's not good.
```css
dialog {
    border-color:#30363d !important;
}
```

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>
